### ISSUE TITLE
Can't open dashboard

### ISSUE THREAD

**Issue by Elikill58** [M-Files/MFilesSamplesAndLibraries#17]
Hi,

I'm trying to use this: https://github.com/M-Files/MFilesSamplesAndLibraries/tree/master/Samples/UIX%20Applications/ShowWebPageInIFrame

But it failed to load.
It don't find the method "ShowDashboard".

![image](https://user-images.githubusercontent.com/17381066/120785210-38148080-c52d-11eb-9687-3f231e20c80f.png)
Sorry it's in french. Its means "The object don't manage property or method "ShowDashboard"".

Full error:
```
CoScriptDelegate_Events.cpp, 400, L’objet ne gère pas la propriété ou la méthode « ShowDashboard » (0x80040008)
IDispatchInvocation.cpp, 96, L’objet ne gère pas la propriété ou la méthode « ShowDashboard » (0x80040008)
Hello World: main.js, 122, L’objet ne gère pas la propriété ou la méthode « ShowDashboard » (0x80040008)
MErrorHelper.cpp, 2457, L’objet ne gère pas la propriété ou la méthode « ShowDashboard » (0x80040008)
(M-Files 21.5.10227.5)
```

**Comment by CraigHawker** [comment]
At first glance the error seems to indicate it's caused by line 122, but the sample in git does not have this many lines.

Please can you confirm that you are using exactly the downloaded sample with Jo modifications?

**Comment by Elikill58** [comment]
Yes, sorry, you're right. It's not the same line.

My line 122 correspond to https://github.com/M-Files/MFilesSamplesAndLibraries/blob/master/Samples/UIX%20Applications/ShowWebPageInIFrame/main.js#L87.

I just edit when this event is called, but i keep two last function.

**Comment by CraigHawker** [comment]
If you use the exact code in the sample then does it throw the exception for you? Or is it just in your altered code?

**Comment by CraigHawker** [comment]
Hi,

I have just downloaded the sample from the repository (with no changes) and deployed it to the local development folder of a vault on my machine.  The sample ran fine on an internal build that I am running (21.6.10322.0).

Please confirm whether or not you receive this error with the exact sample provided, or whether the error appears only with your modified code.

Regards,

Craig.

**Comment by Elikill58** [comment]
Hi,

Sorry, i'm not working this week. I will try in few days and reply as faster as possible.

But thanks you for recall !

**Comment by Elikill58** [comment]
I'm unable to replicate it myself.
Between the bug and now, I reboot my PC. So maybe it fix this error at same time
Now it works fine, so that's perfect, thanks you !
