### ISSUE TITLE
Install Power BI UIX Application

### ISSUE THREAD

**Issue by NFLATSO** [M-Files/MFilesSamplesAndLibraries#23]
Is there any documentary or demo vault showing how to install the PowerBI UIX Application?

**Comment by CraigHawker** [comment]
Not specifically, although the process is the same as any UIX application.  You can either:

 * [install it to the local development folder on your machine (for testing)](https://developer.m-files.com/Frameworks/User-Interface-Extensibility-Framework/Development-Practices/Local-Development-Folder/), or
 * [zip the folder up and install it to the vault (section 3.1.4)](https://www.m-files.com/UI_Extensibility_Framework/index.html#DevGuide.htm) for everyone to see it.

To be clear: the zip should contain the contents of the "PowerBI" folder.
