### ISSUE TITLE
Cannot find MFaaP.MFWSClient in nuget package manager or anywhere

### ISSUE THREAD

**Issue by sayeed1999** [M-Files/MFilesSamplesAndLibraries#44]
I have downloaded MFiles Extension from Visual Studio marketplace,
but i cannot import MFaaP.MFWSClient that is used in all rest api tutorials in sample github projects

how do i include it in my project or find it?

**Comment by CraigHawker** [comment]
The source code is available in github: https://github.com/M-Files/Libraries.MFWSClient.

The package is available in nuget: https://www.nuget.org/packages/MFaaP.MFWSClient/

Note that this is a sample application and not explicitly designed for production use.  For that reason you will notice that the nuget package has a preview flag set; if you only include release packages in your search results then you will not be able to find it.
