### ISSUE TITLE
Postman: InternalID look-up?

### ISSUE THREAD

**Issue by MiroljubA** [M-Files/MFilesSamplesAndLibraries#7]
Hi everyone,
I am trying to create a new object (customer project) with relationships.  To do that I need an InternalID of my existing object (Customer). Did someone manage to do this using the REST API in JSON? 
Can it be done without .NET COM API library? Thanks

**Comment by CraigHawker** [comment]
Hi @MiroljubA.

You can do this using the REST API in the same way as you can with the COM API; when you create the object, you provide it with a PropertyValue which contains the relationship information.

Do you have any specific issue (i.e. a section of one of these samples and libraries which is not working correctly)?  If not then this is not the best forum for such queries; please drop me an email on craig.hawker@m-files.com, including your company/partner name, and we can take a look at how best we can support you.

Regards,

Craig.

**Comment by lcilliers** [comment]
Craig

Was this intended for me?

leR

**Comment by MiroljubA** [comment]
Hi everyone, 
thanks for the quick reply. 
As I said, i need to create a _**Project**_ and give it a _**Customer**_ object as a PropertyDef relation. 
However, this requires a **_InternalID_** not a **_DisplayID_** (the one we use in REST call path.
So my question is how do I obtain **_InternalID_** without using the .NET/VB COM interface.
```
TypedValue :  
           { DataType: 10, 
             Lookup: {
                  ObjID: { Type: 101 Item:<InternalID> } 
                           }
            }
```
@CraigHawker My colleague is already in contact with your support team, however I was hoping for a fast answer here. Thanks.

**Comment by CraigHawker** [comment]
Hi @MiroljubA,

I am going to close this issue.  This is not an issue with the library or sample.

The TypedValue information requires the internal ID, as you said, not the external/display ID.  If you have the external ID then a query to http://www.m-files.com/mfws/resources/objects/type/objectid/version.html (using the external ID in the URI segment) will return you an object containing the object's internal ObjVer, which has its internal ID.

If you continue to have issues and are a customer then please raise this with your reseller (or M-Files account manager, if direct).  If you're a partner, please raise this through your Channel Account Manager, or through support@m-files.com.

Regards,

Craig.
